# fly.toml app configuration file generated for teknologi-umum-captcha on 2024-06-23T10:31:45+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teknologi-umum-captcha'
primary_region = 'cdg'

[build]

[[vm]]
  size = 'shared-cpu-1x'
